version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eForm
    versions:
    - 4.3.14
    - 4.3.17
    - 4.3.18
    - 4.4.13
    - 4.4.14
    - 4.4.17
    - 4.4.19
    - 4.4.20
    - 4.4.22
    - 4.4.3
    - 4.4.6
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.101
    - 2.0.102
    - 2.0.107
    - 2.0.108
    - 2.0.110
    - 2.0.111
    - 2.0.112
    - 2.0.99
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.SqlServer
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: NUnit
    versions:
    - 3.13.0
