//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microting.TimePlanningBase.Resources {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_da {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_da() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microting.TimePlanningBase.Resources.Translations_da", typeof(Translations_da).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Shift_1__start {
            get {
                return ResourceManager.GetString("Shift 1: start", resourceCulture);
            }
        }
        
        internal static string PlanText {
            get {
                return ResourceManager.GetString("PlanText", resourceCulture);
            }
        }
        
        internal static string PlanHours {
            get {
                return ResourceManager.GetString("PlanHours", resourceCulture);
            }
        }
        
        internal static string Shift_1__pause {
            get {
                return ResourceManager.GetString("Shift 1: pause", resourceCulture);
            }
        }
        
        internal static string Comment_office {
            get {
                return ResourceManager.GetString("Comment office", resourceCulture);
            }
        }
        
        internal static string Comment_office_all {
            get {
                return ResourceManager.GetString("Comment office all", resourceCulture);
            }
        }
        
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Flex {
            get {
                return ResourceManager.GetString("Flex", resourceCulture);
            }
        }
        
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        internal static string NettoHours {
            get {
                return ResourceManager.GetString("NettoHours", resourceCulture);
            }
        }
        
        internal static string PaidOutFlex {
            get {
                return ResourceManager.GetString("PaidOutFlex", resourceCulture);
            }
        }
        
        internal static string Shift_1__end {
            get {
                return ResourceManager.GetString("Shift 1: end", resourceCulture);
            }
        }
        
        internal static string Shift_2__end {
            get {
                return ResourceManager.GetString("Shift 2: end", resourceCulture);
            }
        }
        
        internal static string Shift_2__pause {
            get {
                return ResourceManager.GetString("Shift 2: pause", resourceCulture);
            }
        }
        
        internal static string Shift_2__start {
            get {
                return ResourceManager.GetString("Shift 2: start", resourceCulture);
            }
        }
        
        internal static string SumFlex {
            get {
                return ResourceManager.GetString("SumFlex", resourceCulture);
            }
        }
    }
}
